apiVersion: v1
kind: Service
metadata:
  name: angular-starter
  namespace: angular-starter
  labels:
    app: angular-starter
spec:
  type: ClusterIP
  selector:
    app: angular-starter
  ports:
    - name: http
      port: 80
      targetPort: 80
